drop-in compatibility adjustments (#210)
- bump copied generated code to 0.12.1, the last version that had the old package names (includes KtGeneratedFileDescriptor annotation)
- remove old protokt.proto file so that buf is happy that only one file has the protokt extension number
- consolidate jvm extensions modules into multiplatform modules (puts files back in those JARs that were there before the 1.0 reorganization)
- rename protokt outer class to be consistent with protobuf-java
- remove kotlin-reflect from dependencies of protokt-core
- remove interop between old and new generated code, as it is not needed for old generated code to function with the new runtime
- undo manual adjustments to copied generated code as part of the above
- kapt in multiplatform modules fails with: /Users/.../protokt/extensions/protokt-extensions-simple/build/tmp/kapt3/stubs/main/com/toasttab/protokt/ext/LocalDateStringConverter.java:3: error: incompatible types: NonExistentClass cannot be converted to Annotation @error.NonExistentClass(). Not sure what's up.